# Generated by Django 2.1 on 2019-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('diplome', models.CharField(max_length=255)),
                ('specialité', models.CharField(max_length=255)),
                ('Telephone', models.IntegerField()),
            ],
        ),
    ]
