# Generated by Django 2.1 on 2019-04-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialité',
            new_name='specialite',
        ),
    ]
