# Generated by Django 2.1 on 2019-04-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJob', '0002_auto_20190411_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telephone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
