# Generated by Django 2.1 on 2019-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJob', '0003_auto_20190412_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telephone',
            field=models.IntegerField(),
        ),
    ]
