# Generated by Django 2.1 on 2019-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJob', '0004_auto_20190412_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nom'], 'verbose_name': 'user'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialite',
        ),
        migrations.AddField(
            model_name='user',
            name='contenu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=242),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
