# Generated by Django 2.1 on 2019-06-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJob', '0007_auto_20190417_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('compagny', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pubdate', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='competence',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoris',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyJob.Job'),
        ),
        migrations.AddField(
            model_name='favoris',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyJob.Utilisateur'),
        ),
    ]
